name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  task_linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Set Job Vars'
        id: vars
        run: |
          echo "::set-output name=task_version::$(cat ${{ github.workspace }}/.tool-versions | grep -w task | cut -d ' ' -f2)"

      - name: 'Install asdf dependencies'
        uses: asdf-vm/actions/install@v1

      - name: 'Install Task'
        uses: arduino/setup-task@v1.0.1
        with:
          version: ${{ steps.vars.outputs.task_version }}

      - name: Run All Linters
        run: task lint

      - name: Run All Formatters
        run: task format
